### PR TITLE
[RU] Russian translation

### PR DESCRIPTION
**Pull request by ghost**
Initial version of the translation

### CODE REVIEW

**Comment by ManeraKai** [comment]
Apparently @K3XRad turned into a ghost. Do you have any link of him to put it in the README Contributers @Valdnet?

**Comment by Valdnet** [comment]
@ManeraKai I don't have any link. Too bad it will be as a ghost.

**Comment by ManeraKai** [comment]
You informed me that Russian and Malayalam translations will be on their way. Didn't he contact you?

**Comment by Valdnet** [comment]
My friends translated into languages Malayalam and Chinese - Hong Kong.

**Comment by ManeraKai** [comment]
Oh yes, sorry 👍

**Pull request merged**
