### PR TITLE
Reduce font size for empty clipboard

### PR DESCRIPTION
**Pull request by Valdnet**

### CODE REVIEW

**Review by ManeraKai — COMMENTED** [review]
There are more SnackBars in the code. Just search for `SnackBar` on all the files.
Here is how it looks in the standard emulator (FontSize: 18):

What do you think?

**Comment by Valdnet** [comment]
Cool. It is now aligned with the rest 😉.

**Comment by Valdnet** [comment]
Will you change the code yourself? I will close this PR 😉.

**Comment by ManeraKai** [comment]
> Cool. It is now aligned with the rest wink.

I didn't change anything. This was (FontSize: 18)

**Comment by Valdnet** [comment]
> I didn't change anything. This was (FontSize: 18)

I thought you changed the font. My font is bigger. See:

obraz

Here is a comparison with the second "Copied to clipboard" message:

obraz

The same font size should be used 😉.

**Comment by Valdnet** [comment]
Set the font size the same as for "Copied to clipboard" 😉.

**Comment by ManeraKai** [comment]
>The same font size should be used wink.


Your right. Should I change the shape too?

**Comment by Valdnet** [comment]
> Your right. Should I change the shape too?

Yes. I thought about that too 😉.

**Comment by ManeraKai** [comment]
Added changes.

**Comment by Valdnet** [comment]
Center the font for "Updated successfully".

obraz

**Comment by Valdnet** [comment]
@ManeraKai Remember to change it "Updated successfully".

**Comment by ManeraKai** [comment]
??

**Comment by Valdnet** [comment]
Center the font 😁.

**Comment by ManeraKai** [comment]
Oh yeah no worries. I did it. Will come with another commit though.

**Comment by Valdnet** [comment]
@ManeraKai You should also adjust the background width of the information "Updated successfully". Currently, it does not match the length of the text (by no means the Polish translation). In other information, it is more suited to the length of the text.

obraz

For comparison, information for "There was an error" in the same function:

obraz

**Comment by Valdnet** [comment]
I have made changes to PR #104.

**Pull request closed without merging**
